### ISSUE TITLE
How to run the backend and frontend

### ISSUE THREAD

**Issue by Stanka-ai** [pyladies-bratislava/website#17]
How to run the backend and frontend:

1. Create virtual environment #python3 -m venv .venv
2. Activate virtual environment #.\.venv\Scripts\activate
BackEnd
3. Install the requirements #pip install -r requirements.txt
4. Create file .env
5. Start backend (.venv)......\website\backend\flask run

FrontEnd:
6. Install node.js (https://nodejs.org/en/download/)
7. (.venv)......\website\forndend\npm install
8. (.venv)......\website\frontend\npm start

**Comment by Stanka-ai** [comment]
I don't remember how Zuzka helped me to create .env file, but I found this and it worked.

How to create a file in windows terminal: 
1. Type copy con testfile.txt, but replace testfile with the desired file name.
2.Press Enter.
3. Type your desired text. This is rudimentary text editor, but it's good for quick notes or code. You can use the Enter key as you type to move to the next line if you wish.
4. Press Ctrl+Z when you're finished editing the file. This saves everything you've typed into the file.

**Comment by Witchery** [comment]
To the .env file save this information:
FLASK_APP=api
FLASK_ENV=development
