### ISSUE TITLE
What is pyladies section

### ISSUE THREAD

**Issue by filias** [pyladies-bratislava/website#2]

**Comment by DanielaNy** [comment]
Official international Pyladies website: https://pyladies.com/ with about info - may be later scraped and used in our website

**Comment by DanielaNy** [comment]
#24 simple web scraping of Pyladies about info from pyladies.com website was added

**Comment by DanielaNy** [comment]
PR in backend: https://github.com/pyladies-bratislava/flask-backend/pull/13
