### ISSUE TITLE
Create a custom pyladies head for our group

### ISSUE THREAD

**Issue by filias** [pyladies-bratislava/website#48]

**Comment by janakajanova** [comment]
![GP_Dribbble_2732x2048 7](https://user-images.githubusercontent.com/50068453/106199781-4422b700-61b6-11eb-8bc5-a37fe9df668f.png)
![Untitled_Artwork(1)](https://user-images.githubusercontent.com/50068453/106199787-44bb4d80-61b6-11eb-87aa-bf6ad340986d.gif)
![Untitled_Artwork](https://user-images.githubusercontent.com/50068453/106199793-4553e400-61b6-11eb-837b-75e5f108c6af.gif)
![Untitled_Artwork jpg(1)](https://user-images.githubusercontent.com/50068453/106199809-46851100-61b6-11eb-83dd-1d3618810bdb.jpeg)
![Untitled_Artwork jpg(2)](https://user-images.githubusercontent.com/50068453/106199812-471da780-61b6-11eb-90fd-a90dc64183b8.jpeg)
![Untitled_Artwork jpg](https://user-images.githubusercontent.com/50068453/106199816-471da780-61b6-11eb-9449-a456c34a1c2f.jpeg)
![Untitled_Artwork](https://user-images.githubusercontent.com/50068453/106199818-47b63e00-61b6-11eb-991e-56c6027892a2.png)

**Comment by janakajanova** [comment]
![pyladies_ba_white](https://user-images.githubusercontent.com/50068453/112477588-75ad9e00-8d73-11eb-835f-2f3087432958.jpeg)
![pyladies_ba](https://user-images.githubusercontent.com/50068453/112477594-77776180-8d73-11eb-96f7-9b49c4669e89.png)
![pyladies_ba_black](https://user-images.githubusercontent.com/50068453/112477597-780ff800-8d73-11eb-9e61-c8bf13ef226c.png)
