### ISSUE TITLE
How to reach us - fb, slack, email...

### ISSUE THREAD

**Issue by filias** [pyladies-bratislava/website#9]

**Comment by Witchery** [comment]
https://www.facebook.com/groups/PyLadiesBratislava/
https://pyladies.slack.com/archives/CGF33FSMD
https://github.com/pyladies-bratislava
email: bratislava@pyladies.com

![facebook-icon-preview-1](https://user-images.githubusercontent.com/7299647/89585127-986b6080-d83d-11ea-902c-edf39de4ebc5.png)
![Screen_Shot_2019-01-16_at_3 56 35_ 2e16d0ba fill-735x490](https://user-images.githubusercontent.com/7299647/89585155-a4efb900-d83d-11ea-829d-c25bdc7d1c9f.png)
![github-logo-7880D80B8D-seeklogo com](https://user-images.githubusercontent.com/7299647/89585457-2b0bff80-d83e-11ea-963d-6c5b3bb7b0f0.png)

**Comment by DanielaNy** [comment]
email: bratislava@pyladies.com

how-to FB plugin for a webpage: https://developers.facebook.com/docs/plugins/group-plugin

**Comment by filias** [comment]
Added some contacts.
Missing:
1. logos
2. facebook group plugin
